// <auto-generated />
using System;
using BusinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.CohortCurriculum", b =>
                {
                    b.Property<int>("CohortCurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CohortCurriculumId"));

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("CohortCurriculumId");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("Cohort", "CurriculumId")
                        .IsUnique();

                    b.ToTable("CohortCurriculums");
                });

            modelBuilder.Entity("BusinessObject.Curriculum", b =>
                {
                    b.Property<int>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CurriculumId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CurriculumId");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("BusinessObject.Enterprise", b =>
                {
                    b.Property<int>("EnterpriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnterpriseId"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("Industry")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EnterpriseId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("BusinessObject.OJTCondition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConditionId"));

                    b.Property<string>("ConditionKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ConditionId");

                    b.ToTable("OJTConditions");
                });

            modelBuilder.Entity("BusinessObject.OJTFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GivenBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OJTId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("OJTId");

                    b.ToTable("OJTFeedbacks");
                });

            modelBuilder.Entity("BusinessObject.OJTProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramName")
                        .HasColumnType("longtext");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("ProgramId");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("OJTPrograms");
                });

            modelBuilder.Entity("BusinessObject.OJTRegistration", b =>
                {
                    b.Property<int>("OJTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OJTId"));

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OJTId");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("OJTRegistrations");
                });

            modelBuilder.Entity("BusinessObject.OJTResult", b =>
                {
                    b.Property<int>("OJTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OJTId"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<int?>("OJTRegistrationOJTId")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("OJTId");

                    b.HasIndex("OJTRegistrationOJTId");

                    b.ToTable("OJTResults");
                });

            modelBuilder.Entity("BusinessObject.StudentGrade", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("IsPassed")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CASE WHEN Grade >= 5.0 THEN 1 ELSE 0 END");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CurriculumId");

                    b.HasIndex("CurriculumId");

                    b.ToTable("StudentGrades");
                });

            modelBuilder.Entity("BusinessObject.StudentProfile", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<int?>("DebtCredits")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCredits")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Cohort", "CurriculumId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MSSV")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessObject.CohortCurriculum", b =>
                {
                    b.HasOne("BusinessObject.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("BusinessObject.Enterprise", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithOne("Enterprise")
                        .HasForeignKey("BusinessObject.Enterprise", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OJTFeedback", b =>
                {
                    b.HasOne("BusinessObject.OJTRegistration", "OJTRegistration")
                        .WithMany("OJTFeedbacks")
                        .HasForeignKey("OJTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OJTRegistration");
                });

            modelBuilder.Entity("BusinessObject.OJTProgram", b =>
                {
                    b.HasOne("BusinessObject.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("BusinessObject.OJTRegistration", b =>
                {
                    b.HasOne("BusinessObject.Enterprise", "Enterprise")
                        .WithMany("OJTRegistrations")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BusinessObject.OJTProgram", "OJTProgram")
                        .WithMany("OJTRegistrations")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("OJTRegistration")
                        .HasForeignKey("UserId");

                    b.Navigation("Enterprise");

                    b.Navigation("OJTProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.OJTResult", b =>
                {
                    b.HasOne("BusinessObject.OJTRegistration", "OJTRegistration")
                        .WithMany("OJTResults")
                        .HasForeignKey("OJTRegistrationOJTId");

                    b.Navigation("OJTRegistration");
                });

            modelBuilder.Entity("BusinessObject.StudentGrade", b =>
                {
                    b.HasOne("BusinessObject.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.StudentProfile", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("BusinessObject.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BusinessObject.CohortCurriculum", "CohortCurriculum")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("Cohort", "CurriculumId")
                        .HasPrincipalKey("Cohort", "CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CohortCurriculum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.CohortCurriculum", b =>
                {
                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("BusinessObject.Enterprise", b =>
                {
                    b.Navigation("OJTRegistrations");
                });

            modelBuilder.Entity("BusinessObject.OJTProgram", b =>
                {
                    b.Navigation("OJTRegistrations");
                });

            modelBuilder.Entity("BusinessObject.OJTRegistration", b =>
                {
                    b.Navigation("OJTFeedbacks");

                    b.Navigation("OJTResults");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Navigation("Enterprise");

                    b.Navigation("OJTRegistration");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
